[package]
name = "mxgen"
version = "0.1.0"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"

[[bin]]
name = "mxgen"
path = "src/bin/main.rs"

[[bin]]
name = "show"
path = "src/bin/show.rs"

[[bin]]
name = "flatten"
path = "src/bin/flatten.rs"

[lib]
name = "libmxgen"
path = "src/lib.rs"

[dependencies]
derive_more = "0.99.8"
exile = { version = "0.0.2", path = "/Users/mjb/repos/exile/exile" }
indexmap = "1.4.0"
structopt = "0.3.11"
tempfile = "3.1.0"
uuid = { version = "0.8", features = ["v4"] }